### ISSUE TITLE
Onionshare Doesn't Open On Ubuntu 20.04

### ISSUE THREAD

**Issue by gfleetwood** [onionshare/onionshare#1466]
I used snap to install. When I clicked on the icon nothing happened so I went to the command line:

```
$ onionshare
Traceback (most recent call last):
  File "/snap/onionshare/14/bin/onionshare", line 33, in <module>
    sys.exit(load_entry_point('onionshare==2.4', 'console_scripts', 'onionshare')())
  File "/snap/onionshare/14/lib/python3.6/site-packages/onionshare/__init__.py", line 137, in main
    common.display_banner()
  File "/snap/onionshare/14/lib/python3.6/site-packages/onionshare_cli/common.py", line 95, in display_banner
    Back.MAGENTA + Fore.WHITE + "\u256d\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u256e"
  File "/snap/onionshare/14/lib/python3.6/site-packages/colorama/ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "/snap/onionshare/14/lib/python3.6/site-packages/colorama/ansitowin32.py", line 164, in write
    self.wrapped.write(text)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 10-54: ordinal not in range(128)
```

**Comment by pickinanameainteasy** [comment]
Running into a similar issue on openSUSE and Arch Linux

**Comment by micahflee** [comment]
This should be fixed in the next release.
