### ISSUE TITLE
TypeError: cannot set 'is_timeout' attribute of immutable type 'TimeoutError'

### ISSUE THREAD

**Issue by scrazzz** [onionshare/onionshare#1467]
## The problem
I'm facing an issue when using `onionshare-cli` on Termux.

-----

### Command
`onionshare-cli --help`

### Error
```py
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/onionshare-cli", line 5, in <module>
      from onionshare_cli import main
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/onionshare_cli/__init__.py", line 30, in <module>
      from .web import Web
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/onionshare_cli/web/__init__.py", line 21, in <module>
      from .web import Web
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/onionshare_cli/web/web.py", line 38, in <module>
      from flask_socketio import SocketIO
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/flask_socketio/__init__.py", line 9, in <module>
      from socketio import socketio_manage  # noqa: F401
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/socketio/__init__.py", line 9, in <module>
      from .zmq_manager import ZmqManager
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/socketio/zmq_manager.py", line 5, in <module>
      import eventlet.green.zmq as zmq
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/eventlet/__init__.py", line 17, in <module>
      from eventlet import convenience
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/eventlet/convenience.py", line 7, in <module>
      from eventlet.green import socket
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/eventlet/green/socket.py", line 4, in <module>
      __import__('eventlet.green._socket_nodns')
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/eventlet/green/_socket_nodns.py", line 11, in <module>
      from eventlet import greenio
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/eventlet/greenio/__init__.py", line 3, in <module>
      from eventlet.greenio.base import *  # noqa
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/eventlet/greenio/base.py", line 32, in <module>
      socket_timeout = eventlet.timeout.wrap_is_timeout(socket.timeout)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/eventlet/timeout.py", line 166, in wrap_is_timeout
      base.is_timeout = property(lambda _: True)
TypeError: cannot set 'is_timeout' attribute of immutable type 'TimeoutError'
```

**Comment by mig5** [comment]
It looks like a bug in the 'eventlet' Python module on Python 3.10 - not a bug in OnionShare as such. https://github.com/eventlet/eventlet/issues/687
