### ISSUE TITLE
Tests fail for onionshare-desktop on openSUSE Tumbleweed / Invalid async_mode specified (affects ArchLinux too)

### ISSUE THREAD

**Issue by coogor** [onionshare/onionshare#1510]
Hi, building the latest onionshare (2.5) for openSUSE Tumbleweed I ran in a couple of 'Assertion Errors', see attached.

[testresults.txt](https://github.com/onionshare/onionshare/files/7896968/testresults.txt)

Any suggestion?
Thanks!

**Comment by susnux** [comment]
The root of this issue is the missing gevent package:

```
[   23s]   File "/usr/lib/python3.8/site-packages/engineio/server.py", line 145, in __init__
[   23s]     raise ValueError('Invalid async_mode specified')
[   23s] ValueError: Invalid async_mode specified
```

Here
https://github.com/onionshare/onionshare/blob/c6e0aafc1d35c545446742f01982a9579be7cfaa/cli/onionshare_cli/web/web.py#L167
and here
https://github.com/onionshare/onionshare/blob/c6e0aafc1d35c545446742f01982a9579be7cfaa/cli/onionshare_cli/web/web.py#L170

`gevent` is requested (`gevent-socketio`).

So either install `gevent-socketio` or remove the `async_mode` parameter to allow SocketIO to decide which mode to take (prefers `eventlet`, which is available on openSUSE unlike `gevent-socketio`).

**Comment by bavier** [comment]
FWIW, the GNU Guix package manager recently adopted this patch for its `onionshare` package:

```diff
diff --git a/cli/onionshare_cli/web/web.py b/cli/onionshare_cli/web/web.py                                                                                                                                                                     
index 64844b5..7e1b095 100644                                                                                                                                                                                                                  
--- a/cli/onionshare_cli/web/web.py                                                                                                                                                                                                            
+++ b/cli/onionshare_cli/web/web.py                                                                                                                                                                                                            
@@ -164,10 +164,10 @@ class Web:                                                                                                                                                                                                               
         elif self.mode == "chat":                                                                                                                                                                                                             
             if self.common.verbose:                                                                                                                                                                                                           
                 self.socketio = SocketIO(                                                                                                                                                                                                     
-                    async_mode="gevent", logger=True, engineio_logger=True                                                                                                                                                                    
+                    logger=True, engineio_logger=True                                                                                                                                                                                         
                 )                                                                                                                                                                                                                             
             else:                                                                                                                                                                                                                             
-                self.socketio = SocketIO(async_mode="gevent")                                                                                                                                                                                 
+                self.socketio = SocketIO()                                                                                                                                                                                                    
             self.socketio.init_app(self.app)                                                                                                                                                                                                  
             self.chat_mode = ChatModeWeb(self.common, self)
```

GNU Guix does not have `gevent-socketio` packaged, and that project is rather unmaintained anyhow, so this patch allows `eventlet` to be used instead.

The commit that added these parameters (ec7fa4ef16c9e1ba6028ee927c23f76c399a17a6) seemed to do so for purely Windows and macOS packaging, rather than functional, reasons.

**Comment by bavier** [comment]
@coogor the desktop tests that failed originally seem to now be disabled.  I cannot run those tests myself at the moment, for other reasons.  Those tests are where this issue would appear, I believe, or when opening a Chat tab.

**Comment by coogor** [comment]
@bavier you are right, my bad.
Your guess with a chat tab is quite likely, it crashes first time in test_gui_tabs.py (and in all others as well)

**Comment by bavier** [comment]
@mig5 In the absence of gevent, my OS has the 'threading' and 'eventlet' modes available, with 'flask.SocketIO' preferring 'eventlet' if available before falling back to 'threading'.

Sorry for the wall of text. I'm trying to understand a little more of what's going on here, forgive me, I'm not a web developer.  I'm hoping sharing some of what I'm seeing can help you and others figure out what might be going on.

My current patch is:
```diff
--- a/cli/onionshare_cli/web/web.py                                                                                                                                          
+++ b/cli/onionshare_cli/web/web.py                                                                                                                                          
@@ -175,19 +175,15 @@                                                                                                                                                        
         elif self.mode == "website":                                                                                                                                        
             self.website_mode = WebsiteModeWeb(self.common, self)                                                                                                           
         elif self.mode == "chat":                                                                                                                                           
-            if self.common.verbose:                                                                                                                                         
-                try:                                                                                                                                                        
-                    self.socketio = SocketIO(                                                                                                                               
-                        async_mode="gevent", logger=True, engineio_logger=True                                                                                              
-                    )                                                                                                                                                       
-                except ValueError:                                                                                                                                          
-                    self.socketio = SocketIO(logger=True, engineio_logger=True)                                                                                             
-            else:                                                                                                                                                           
-                try:                                                                                                                                                        
-                    self.socketio = SocketIO(async_mode="gevent")                                                                                                           
-                except ValueError:                                                                                                                                          
-                    self.socketio = SocketIO()                                                                                                                              
-            self.socketio.init_app(self.app)                                                                                                                                
+            try:                                                                                                                                                            
+                self.socketio = SocketIO(app=self.app,                                                                                                                      
+                                         async_mode="gevent",                                                                                                               
+                                         logger=self.common.verbose,                                                                                                        
+                                         engineio_logger=self.common.verbose)                                                                                               
+            except ValueError:                                                                                                                                              
+                self.socketio = SocketIO(app=self.app,                                                                                                                      
+                                         logger=self.common.verbose,                                                                                                        
+                                         engineio_logger=self.common.verbose)                                                                                               
             self.chat_mode = ChatModeWeb(self.common, self)                                                                                                                 
                                                                                                                                                                             
         self.cleanup_tempdirs = []                                                                                                                                          
@@ -359,7 +355,8 @@                                                                                                                                                          
                                                                                                                                                                             
         self.running = True                                                                                                                                                 
         if self.mode == "chat":                                                                                                                                             
-            self.socketio.run(self.app, host=host, port=port)                                                                                                               
+            self.socketio.run(self.app, host=host, port=port,                                                                                                               
+                              allow_unsafe_werkzeug=True)                                                                                                                   
         else:                                                                                                                                                               
             try:                                                                                                                                                            
                 self.waitress = create_server(
```
Passing the `app` argument is valid here, since it already available at this point, and triggers immediate initialization inside the `try/except`.  Currently, the relevant error would be thrown from `init_app`'s deferred initialization.

The `allow_unsafe_werkzeug=True` is related to some debugging I'm still working on.  This argument prevents an error from [flask.SocketIO.run()](https://github.com/miguelgrinberg/Flask-SocketIO/blob/78dda9b64b275f9962d7a40de0db411b6aafac07/src/flask_socketio/__init__.py#L650) when `eventlet` is not available.  Unfortunately there appear to be other issues possibly related to thread creation and destruction in this mode:

```
==================================== ERRORS ====================================
__ ERROR at teardown of TestTabs.test_15_quit_with_server_started_should_warn __

cls = <class 'tests.test_gui_tabs.TestTabs'>

    @classmethod
    def tearDownClass(cls):
        # Quit
        cls.gui.qtapp.clipboard().clear()
        QtCore.QTimer.singleShot(200, cls.gui.close_dialog.accept_button.click)
        cls.gui.close()

>       cls.gui.cleanup()

tests/gui_base_test.py:81:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
onionshare/main_window.py:288: in cleanup
    self.tabs.cleanup()
onionshare/tab_widget.py:104: in cleanup
    self.tabs[tab_id].cleanup()
onionshare/tab/tab.py:678: in cleanup
    self.get_mode().web.stop(self.get_mode().app.port)
/gnu/store/kijvk8s46q18455n3xl5v5phnlpk7nkw-onionshare-cli-2.6.3/lib/python3.10/site-packages/onionshare_cli/web/web.py:385: in stop
    self.socketio.stop()
/gnu/store/58c0lpwsh1ddifrkijzmk15yd4hjqc66-python-flask-socketio-5.5.1/lib/python3.10/site-packages/flask_socketio/__init__.py:734: in stop
    func = flask.request.environ.get('werkzeug.server.shutdown')
/gnu/store/fn01hy36j3r3faqnhwq9jrk3zk5q1nc1-python-werkzeug-3.1.3/lib/python3.10/site-packages/werkzeug/local.py:318: in __get__
    obj = instance._get_current_object()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def _get_current_object() -> T:
        try:
            obj = local.get()
        except LookupError:
>           raise RuntimeError(unbound_message) from None
E           RuntimeError: Working outside of request context.
E
E           This typically means that you attempted to use functionality that needed
E           an active HTTP request. Consult the documentation on testing for
E           information about how to avoid this problem.

/gnu/store/fn01hy36j3r3faqnhwq9jrk3zk5q1nc1-python-werkzeug-3.1.3/lib/python3.10/site-packages/werkzeug/local.py:519: RuntimeError
--------------------------- Captured stdout teardown ---------------------------
[Mar 27 2025 04:36:40] MainWindow.closeEvent
[Mar 27 2025 04:36:40] MainWindow.closeEvent, opening warning dialog
[Mar 27 2025 04:36:41] MainWindow.cleanup
[Mar 27 2025 04:36:41] TabWidget.cleanup
[Mar 27 2025 04:36:41] Tab.cleanup: tab_id=12
[Mar 27 2025 04:36:41] Web.stop: stopping server
--------------------------- Captured stderr teardown ---------------------------
This plugin does not support propagateSizeHints()
```

Ignoring these test errors, I am able to start a Chat window, but the server seems to not be stopped completely when the "Stop" button is clicked in the tab, e.g. clients don't get "server disconnected" notices and can continue to send messages to each other.  Documentation says repeatedly not use use the werkzeug threaded server "in production", but I feel like using it in Onionshare would not be a terrible idea if the kinks were worked out.

With the OS's current `python-eventlet` version 0.38.2 package and the latest 0.39.1 version (both current and latest `python-trio`), I got an  "AttributeError: type object 'GreenSocket' has no attribute 'sendmsg'", suggesting non-conformance with the `socket` API:

```
  File "/gnu/store/c7wdgd9afgaxx8zk0aariw4c0q1mkmxh-python-engineio-4.11.2/lib/python3.10/site-packages/engineio/async_drivers/eventlet.py", line 1, in <module>
    from eventlet.green.threading import Event
  File "/gnu/store/0889hc07p8vrgmbbq1f81amxcxp5dnj3-python-eventlet-0.39.1/lib/python3.10/site-packages/eventlet/__init__.py", line 6, in <module>
    from eventlet import convenience
  File "/gnu/store/0889hc07p8vrgmbbq1f81amxcxp5dnj3-python-eventlet-0.39.1/lib/python3.10/site-packages/eventlet/convenience.py", line 7, in <module>
    from eventlet.green import socket
  File "/gnu/store/0889hc07p8vrgmbbq1f81amxcxp5dnj3-python-eventlet-0.39.1/lib/python3.10/site-packages/eventlet/green/socket.py", line 21, in <module>
    from eventlet.support import greendns
  File "/gnu/store/0889hc07p8vrgmbbq1f81amxcxp5dnj3-python-eventlet-0.39.1/lib/python3.10/site-packages/eventlet/support/greendns.py", line 78, in <module>
    setattr(dns, pkg, import_patched('dns.' + pkg))
  File "/gnu/store/0889hc07p8vrgmbbq1f81amxcxp5dnj3-python-eventlet-0.39.1/lib/python3.10/site-packages/eventlet/support/greendns.py", line 60, in import_patched
    return patcher.import_patched(module_name, **modules)
  File "/gnu/store/0889hc07p8vrgmbbq1f81amxcxp5dnj3-python-eventlet-0.39.1/lib/python3.10/site-packages/eventlet/patcher.py", line 136, in import_patched
    return inject(
  File "/gnu/store/0889hc07p8vrgmbbq1f81amxcxp5dnj3-python-eventlet-0.39.1/lib/python3.10/site-packages/eventlet/patcher.py", line 113, in inject
    module = __import__(module_name, {}, {}, module_name.split(".")[:-1])
  File "/gnu/store/2s7lh95g5q1n0czh52zly35ljazbfwvq-python-dnspython-2.7.0/lib/python3.10/site-packages/dns/asyncquery.py", line 34, in <module>
    import dns.quic
  File "/gnu/store/2s7lh95g5q1n0czh52zly35ljazbfwvq-python-dnspython-2.7.0/lib/python3.10/site-packages/dns/quic/__init__.py", line 39, in <module>
    import trio
  File "/gnu/store/xn5andhd4w3j807lj4dipsxyh9q2mj92-python-trio-0.28.0/lib/python3.10/site-packages/trio/__init__.py", line 26, in <module>
    from . import abc, from_thread, lowlevel, socket, to_thread
  File "/gnu/store/xn5andhd4w3j807lj4dipsxyh9q2mj92-python-trio-0.28.0/lib/python3.10/site-packages/trio/socket.py", line 16, in <module>
    from . import _socket
  File "/gnu/store/xn5andhd4w3j807lj4dipsxyh9q2mj92-python-trio-0.28.0/lib/python3.10/site-packages/trio/_socket.py", line 543, in <module>
    class SocketType:
  File "/gnu/store/xn5andhd4w3j807lj4dipsxyh9q2mj92-python-trio-0.28.0/lib/python3.10/site-packages/trio/_socket.py", line 756, in SocketType
    @_wraps(_stdlib_socket.socket.sendmsg, assigned=(), updated=())
AttributeError: type object 'GreenSocket' has no attribute 'sendmsg'
```

Being a different type of error, the new `try/except` doesn't catch this, and onionshare continues without a webserver, and we get the `error: 'NoneType' object has no attribute 'q'` (maybe related to issue #1909) which causes many tests to fail, and makes the Chat feature completely unusable: the tab contents render in a separate window with buttons missing, and inability to close the Chat tab itself.  In the console there are repeated messages:

```
Traceback (most recent call last):
  File "/gnu/store/7h0kg8x7f469dm7rmp98h7wfvbmn0p1g-onionshare-2.6.3/lib/python3.10/site-packages/onionshare/tab/tab.py", line 540, in timer_callback
    r = mode.web.q.get(False)
AttributeError: 'NoneType' object has no attribute 'q'
```

And when Onionshare is exited:

```
Traceback (most recent call last):
  File "/gnu/store/7h0kg8x7f469dm7rmp98h7wfvbmn0p1g-onionshare-2.6.3/lib/python3.10/site-packages/onionshare/__init__.py", line 259, in shutdown
    main_window.cleanup()
  File "/gnu/store/7h0kg8x7f469dm7rmp98h7wfvbmn0p1g-onionshare-2.6.3/lib/python3.10/site-packages/onionshare/main_window.py", line 288, in cleanup
    self.tabs.cleanup()
  File "/gnu/store/7h0kg8x7f469dm7rmp98h7wfvbmn0p1g-onionshare-2.6.3/lib/python3.10/site-packages/onionshare/tab_widget.py", line 104, in cleanup
    self.tabs[tab_id].cleanup()
  File "/gnu/store/7h0kg8x7f469dm7rmp98h7wfvbmn0p1g-onionshare-2.6.3/lib/python3.10/site-packages/onionshare/tab/tab.py", line 682, in cleanup
    self.get_mode().web.cleanup()
AttributeError: 'NoneType' object has no attribute 'cleanup'
QThread: Destroyed while thread is still running
Aborted
```
