### ISSUE TITLE
Problem in hosting website "Sorry, an unexpected error seems to have occurred, and your request didn't succeed"

### ISSUE THREAD

**Issue by ShadowSocks12** [onionshare/onionshare#1512]
Hi, I try to upload a file using "Host a Website" Feature  but when clicking on the file name  I get this message "Sorry, an unexpected error seems to have occurred, and your request didn't succeed", 
This happens with any file whether its type is .pdf or .txt or any other type.

![image](https://user-images.githubusercontent.com/63942376/150263950-f9b22f9a-a2be-45ce-8081-958bd4ed42e9.png)
![image](https://user-images.githubusercontent.com/63942376/150263634-54b773bd-ed9d-4734-ba95-328e8bd6ca5e.png)

I use onionshare version 2.5 on windows.
What do I do? 
And thank you very much.

**Comment by RaidenMK** [comment]
I got the same issue too as you and I just sent an email to micah about it just in case

**Comment by nasekh** [comment]
hello. did you fix that issue? hit me if you fixed. i got the same problem

**Comment by driggerspaxton** [comment]
hi, I'm having the exact same problem

**Comment by RaidenMK** [comment]
- This is what I do:
1.) I open onionshare 2.5
2.) Choose "Share Files" option.
3.) Drag any files to the "Share Files" window and then click "Start sharing" and it creates a random link.
4.) I then open the generated link with the file that is uploaded.
5.) then I click the file to try display it. But when I click it,thats where I get the error "Sorry, an unexpected error seems to have occurred, and your request didn't succeed".. 

It is fine to upload and download files. its just when I display the file I get the error,

I am using Windows 11 Home 64bit

**Comment by mig5** [comment]
Hi everyone. I have reproduced the issue and confirm it is a bug in the Windows version of OnionShare.

There is no workaround for the issue, I'm afraid. You'll have to wait for a new release that contains a fix. There is no ETA for this fix.

@micahflee, it seems to relate to the TemporaryFile changes. In my tests downloading the 'zip' file works, but individual files (Share or Website mode) throw the below permission error, I feel like we solved this already somewhere else.

```
[2022-02-07 12:11:45,068] ERROR in app: Exception on /README.md [GET]
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\onionshare-XYHOyDCw-py3.9\lib\site-packages\flask\app.py", line 2447, in wsgi_app
  File "C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\onionshare-XYHOyDCw-py3.9\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
  File "C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\onionshare-XYHOyDCw-py3.9\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
  File "C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\onionshare-XYHOyDCw-py3.9\lib\site-packages\flask\_compat.py", line 39, in reraise
  File "C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\onionshare-XYHOyDCw-py3.9\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
  File "C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\onionshare-XYHOyDCw-py3.9\lib\site-packages\flask\app.py", line 1936, in dispatch_request
  File "C:\Users\User\code\onionshare\cli\onionshare_cli\web\website_mode.py", line 43, in path_public
  File "C:\Users\User\code\onionshare\cli\onionshare_cli\web\website_mode.py", line 49, in path_logic
  File "C:\Users\User\code\onionshare\cli\onionshare_cli\web\website_mode.py", line 96, in render_logic
  File "C:\Users\User\code\onionshare\cli\onionshare_cli\web\send_base_mode.py", line 200, in stream_individual_file
  File "C:\Users\User\code\onionshare\cli\onionshare_cli\web\send_base_mode.py", line 315, in _gzip_compress
  File "C:\Users\User\AppData\Local\Programs\Python\Python39-32\lib\gzip.py", line 58, in open
  File "C:\Users\User\AppData\Local\Programs\Python\Python39-32\lib\gzip.py", line 173, in __init__
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\migue\\AppData\\Roaming\\OnionShare\\tmp\\tmpimfdgyg1'
127.0.0.1 - - [07/Feb/2022 12:11:45] "GET /README.md HTTP/1.1" 500 -
127.0.0.1 - - [07/Feb/2022 12:11:46] "GET /static_wozi5e5d7sulw32gszjicrlk34/img/logo_large.png HTTP/1.1" 200 -
```

**Comment by RaidenMK** [comment]
So what is best to do then due to the error? Just wait to use onionshare until its ficed and new version comes or go back to version 2.4 until its fixed?

**Comment by mig5** [comment]
Just wait til it's fixed, or (if using Share mode) don't try to download individual files - instead use the purple Download button which gives you a zip of all the files together, and I believe works fine.

**Comment by micahflee** [comment]
I've figured out what the bug is. When downloading an individual file, it gzip compresses it to disk first into a temporary file. It creates the temp file by using [tempfile.NamedTemporaryFile](https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile), which includes. This function not only creates a temporary file but then opens the file. The docs say:

>  Whether the name can be used to open the file a second time, while the named temporary file is still open, varies across platforms (it can be so used on Unix; it cannot on Windows NT or later).

**Comment by RaidenMK** [comment]
So when you think that issue will be solved so I can finally use onionshare 2.5's share file feature again? I miss the filesharing

**Comment by sandyvb** [comment]
I am experiencing the same issue. Even this simple index.html doc produces the same error message as above.

<!DOCTYPE html>
<html>
   <body>
      <h1>Heading</h1>
      <p>paragraph</p>
   </body>
</html>

**Comment by cscortes** [comment]
Has this fix been pushed to production yet?  I am still seeing the same error when I try webhosting.

**Comment by mig5** [comment]
No, it's not yet been released.

**Comment by mydgz** [comment]
Fuck onion abaré bug shit!! This sux program dont work
