### ISSUE TITLE
Outdated dependencies breaks onionshare

### ISSUE THREAD

**Issue by 3nprob** [onionshare/onionshare#1536]
See https://github.com/pallets/flask/issues/4455 - subdependencies of flask have released minor updates including breaking changes causing onionshare to exit with error on startup.

Flask really should be updated but in the interim this can be resolved by pinning the right dependencies (see above issue)

Related issue: #1527 

```
Traceback (most recent call last):
  File "/usr/local/bin/onionshare-cli", line 5, in <module>
    from onionshare_cli import main
  File "/usr/local/lib/python3.10/site-packages/onionshare_cli/__init__.py", line 30, in <module>
    from .web import Web
  File "/usr/local/lib/python3.10/site-packages/onionshare_cli/web/__init__.py", line 21, in <module>
    from .web import Web
  File "/usr/local/lib/python3.10/site-packages/onionshare_cli/web/web.py", line 28, in <module>
    import flask
  File "/usr/local/lib/python3.10/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
  File "/usr/local/lib/python3.10/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/usr/local/lib/python3.10/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/usr/local/lib/python3.10/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.10/site-packages/markupsafe/__init__.py)
```

**Comment by mig5** [comment]
Fixed via https://github.com/onionshare/onionshare/pull/1541
