### ISSUE TITLE
OnionShare won't start after last update

### ISSUE THREAD

**Issue by peter099** [onionshare/onionshare#1597]
After the last update OnionShare won't launch. This is the log from the terminal:

```
$ flatpak run org.onionshare.OnionShare 
Traceback (most recent call last):
  File "/app/bin/onionshare", line 33, in <module>
    sys.exit(load_entry_point('onionshare==2.5', 'console_scripts', 'onionshare')())
  File "/app/bin/onionshare", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/app/lib/python3.9/site-packages/onionshare-2.5-py3.9.egg/onionshare/__init__.py", line 34, in <module>
  File "/app/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "<frozen zipimport>", line 259, in load_module
  File "/app/lib/python3.9/site-packages/onionshare_cli-2.5-py3.9.egg/onionshare_cli/__init__.py", line 30, in <module>
  File "/app/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "<frozen zipimport>", line 259, in load_module
  File "/app/lib/python3.9/site-packages/onionshare_cli-2.5-py3.9.egg/onionshare_cli/web/__init__.py", line 21, in <module>
  File "/app/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "<frozen zipimport>", line 259, in load_module
  File "/app/lib/python3.9/site-packages/onionshare_cli-2.5-py3.9.egg/onionshare_cli/web/web.py", line 28, in <module>
  File "/app/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/app/lib/python3.9/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
  File "/app/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/app/lib/python3.9/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/app/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/app/lib/python3.9/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/app/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/app/lib/python3.9/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/app/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/app/lib/python3.9/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/lib/python3.9/site-packages/markupsafe/__init__.py)
```

I am using MX Linux.

**Comment by mig5** [comment]
Hi,

It's a known issue that's already been fixed in git. The next release will contain the fix (hopefully coming out very soon). Sorry for the inconvenience.

https://github.com/onionshare/onionshare/issues/1536
https://github.com/onionshare/onionshare/issues/1585
