### ISSUE TITLE
OnionShare v2.5 does not start anymore - Debian Gnome stable/testing - flatpak cli/gui

### ISSUE THREAD

**Issue by qufo418** [onionshare/onionshare#1600]
Hi everybody, today I noticed that OnionShare won't start anymore. There was an KDE platform update today. Below the details. In case you need more let me know.

**Following the verbose CLI output (the gui produces nothing)**:
```
$>flatpak run --verbose org.onionshare.OnionShare
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/u1/.local/share/flatpak
F: Opening user flatpak installation at path /home/u1/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/u1/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Regenerating ld.so.cache /home/u1/.var/app/org.onionshare.OnionShare/.ld.so/2c65db0002e4ee267d9a4ff3c8fb4994d2b46dfa85eed923b07b065ffd5c8c12
F: /var/lib/flatpak/runtime/org.kde.Platform/x86_64/5.15-21.08/497a0d244beeb1308837e356ec9a39dfdaf23d9de18998aeaaa05f171f0415a2/files/lib32 does not exist
F: Running: 'bwrap --args 27 ldconfig -X -C /run/ld-so-cache-dir/2c65db0002e4ee267d9a4ff3c8fb4994d2b46dfa85eed923b07b065ffd5c8c12.o1G4gq'
F: /var/lib/flatpak/runtime/org.kde.Platform/x86_64/5.15-21.08/497a0d244beeb1308837e356ec9a39dfdaf23d9de18998aeaaa05f171f0415a2/files/lib32 does not exist
F: Cleaning up unused container id 2981383100
F: Cleaning up per-app-ID state for org.onionshare.OnionShare
F: Allocated instance id 1249218188
F: Add defaults in dir /org/onionshare/OnionShare/
F: Add locks in dir /org/onionshare/OnionShare/
F: Allowing dri access
F: Allowing wayland access
F: Allowing x11 access
F: Running 'bwrap --args 43 xdg-dbus-proxy --args=45'
F: Running 'bwrap --args 43 onionshare'
Traceback (most recent call last):
  File "/app/bin/onionshare", line 33, in <module>
    sys.exit(load_entry_point('onionshare==2.5', 'console_scripts', 'onionshare')())
  File "/app/bin/onionshare", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/app/lib/python3.9/site-packages/onionshare-2.5-py3.9.egg/onionshare/__init__.py", line 34, in <module>
  File "/app/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
 File "<frozen zipimport>", line 259, in load_module
  File "/app/lib/python3.9/site-packages/onionshare_cli-2.5-py3.9.egg/onionshare_cli/__init__.py", line 30, in <module>
  File "/app/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "<frozen zipimport>", line 259, in load_module
  File "/app/lib/python3.9/site-packages/onionshare_cli-2.5-py3.9.egg/onionshare_cli/web/__init__.py", line 21, in <module>
  File "/app/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "<frozen zipimport>", line 259, in load_module
  File "/app/lib/python3.9/site-packages/onionshare_cli-2.5-py3.9.egg/onionshare_cli/web/web.py", line 28, in <module>
  File "/app/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/app/lib/python3.9/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
  File "/app/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/app/lib/python3.9/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/app/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/app/lib/python3.9/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/app/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/app/lib/python3.9/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/app/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/app/lib/python3.9/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/lib/python3.9/site-packages/markupsafe/__init__.py)
```

**Output of flatpak list --verbose:**
```
$>flatpak list --verbose
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/u1/.local/share/flatpak
AnyDesk	com.anydesk.Anydesk	6.1.1	stable	system
Weasis	io.github.nroduit.Weasis	4.0.1	stable	system
Freedesktop Platform	org.freedesktop.Platform	21.08.14	21.08	system
Mesa	org.freedesktop.Platform.GL.default	21.1.8	20.08	system
Mesa	org.freedesktop.Platform.GL.default	21.3.8	21.08	system
openh264	org.freedesktop.Platform.openh264	2.1.0	2.0	system
Freedesktop SDK	org.freedesktop.Sdk	21.08.14	21.08	system
Adwaita dark GTK theme	org.gtk.Gtk3theme.Adwaita-dark		3.22	system
Adwaita theme	org.kde.KStyle.Adwaita		5.15	system
Adwaita theme	org.kde.KStyle.Adwaita		5.15-21.08	system
Adwaita theme	org.kde.KStyle.Adwaita		6.2	system
KDE Application Platform	org.kde.Platform		5.15-21.08	system
KDE Application Platform	org.kde.Platform		6.2	system
QGnomePlatform	org.kde.PlatformTheme.QGnomePlatform		5.15	system
QGnomePlatform	org.kde.PlatformTheme.QGnomePlatform		5.15-21.08	system
QGnomePlatform	org.kde.PlatformTheme.QGnomePlatform		6.2	system
QGnomePlatform sourcecode	org.kde.PlatformTheme.QGnomePlatform.Sources		5.15	system
QtSNI	org.kde.PlatformTheme.QtSNI		5.15	system
QtSNI	org.kde.PlatformTheme.QtSNI		5.15-21.08	system
QtSNI sourcecode	org.kde.PlatformTheme.QtSNI.Sources		5.15	system
QGnomePlatform-decoration	org.kde.WaylandDecoration.QGnomePlatform-decoration		5.15	system
QGnomePlatform-decoration	org.kde.WaylandDecoration.QGnomePlatform-decoration		5.15-21.08	system
QGnomePlatform-decoration	org.kde.WaylandDecoration.QGnomePlatform-decoration		6.2	system
QGnomePlatform_decoration sourcecode	org.kde.WaylandDecoration.QGnomePlatform_decoration.Sources		5.15	system
OnionShare	org.onionshare.OnionShare	2.5	stable	system
```
**Installed flatpak components:**
```
$>aptitude versions --group-by=none '~nflatpak' | egrep '^i'
i  flatpak 1.12.7-1 testing,unstable 990
i  gnome-software-plugin-flatpak 42.2-1 testing,unstable 990
i A libflatpak0 1.12.7-1 testing,unstable 990
```

Both outputs are taken from Debian Gnome Testing, but it's the same on Stable. The systems in question are VMs (KVM/QEMU) on Manjaro Linux (kernel 5.18.7-1-MANJARO #1 SMP PREEMPT_DYNAMIC Sun Jun 26 07:06:41 UTC 2022 x86_64 GNU/Linux)

Regards.

**Comment by firefoxlover** [comment]
This also occurs on Kubuntu 22.04.

GUI doesnt start, CLI gives a different error for me:

```
user@laptop:~$ onionshare --stay-open /home/user/folder
OnionShare 2.2 | https://onionshare.org/
Traceback (most recent call last):
  File "/usr/bin/onionshare", line 22, in <module>
    onionshare.main()
  File "/usr/lib/python3/dist-packages/onionshare/__init__.py", line 181, in main
    web = Web(common, False, mode)
  File "/usr/lib/python3/dist-packages/onionshare/web/web.py", line 77, in __init__
    self.generate_static_url_path()
  File "/usr/lib/python3/dist-packages/onionshare/web/web.py", line 166, in generate_static_url_path
    self.app.add_url_rule(
  File "/usr/lib/python3/dist-packages/flask/scaffold.py", line 56, in wrapper_func
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1092, in add_url_rule
    raise AssertionError(
AssertionError: View function mapping is overwriting an existing endpoint function: static
```

**Comment by mig5** [comment]
https://github.com/onionshare/onionshare/issues?q=cannot+import+name+%27soft_unicode%27+from+%27markupsafe%27

The issue (reported 4 times now!) has been fixed in git, it will be in the next release.
