### ISSUE TITLE
flatpak doesn't launch on linux mint 21

### ISSUE THREAD

**Issue by akirapink** [onionshare/onionshare#1646]
the flatpak just doesn't work on mint 21?
the stated reason is that it can't find `markupsafe`, and apparently this has happened to other people with other projects, but the solution for them (using a different version than 2.0.1) doesn't work for me
the flatpak continues to insist that markupsafe doesn't exist
what do i do?

```
akira~:$flatpak run  org.onionshare.OnionShare
Traceback (most recent call last):
  File "/app/bin/onionshare", line 33, in <module>
    sys.exit(load_entry_point('onionshare==2.6', 'console_scripts', 'onionshare')())
  File "/app/bin/onionshare", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/app/lib/python3.9/site-packages/onionshare-2.6-py3.9.egg/onionshare/__init__.py", line 34, in <module>
  File "/app/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "<frozen zipimport>", line 259, in load_module
  File "/app/lib/python3.9/site-packages/onionshare_cli-2.6-py3.9.egg/onionshare_cli/__init__.py", line 30, in <module>
  File "/app/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "<frozen zipimport>", line 259, in load_module
  File "/app/lib/python3.9/site-packages/onionshare_cli-2.6-py3.9.egg/onionshare_cli/web/__init__.py", line 21, in <module>
  File "/app/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "<frozen zipimport>", line 259, in load_module
  File "/app/lib/python3.9/site-packages/onionshare_cli-2.6-py3.9.egg/onionshare_cli/web/web.py", line 28, in <module>
  File "/app/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/app/lib/python3.9/site-packages/flask/__init__.py", line 1, in <module>
    from markupsafe import escape
  File "/app/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'markupsafe'
```

**Comment by mig5** [comment]
I think this issue should be well resolved in 2.6.1, but please reopen if not.
