### ISSUE TITLE
cant run in manjaro

### ISSUE THREAD

**Issue by dzwdev** [onionshare/onionshare#1898]
iget this error:

```
Traceback (most recent call last):
  File "/usr/bin/onionshare", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/onionshare/__init__.py", line 251, in main
    main_window = MainWindow(common, filenames)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/onionshare/main_window.py", line 151, in __init__
    self.show()
  File "/usr/lib/python3.11/site-packages/onionshare/main_window.py", line 277, in event
    return QtWidgets.QMainWindow.event(self, event)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/onionshare/main_window.py", line 319, in resizeEvent
    return super(MainWindow, self).resizeEvent(event)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'PySide6.QtWidgets.QWidget.resizeEvent' called with wrong argument types:
  PySide6.QtWidgets.QWidget.resizeEvent(QEvent)
Supported signatures:
  PySide6.QtWidgets.QWidget.resizeEvent(PySide6.QtGui.QResizeEvent)
QThread: Destroyed while thread is still running
zsh: IOT instruction (core dumped)  onionshare
```

**Comment by SuperSandro2000** [comment]
Please test #1903

**Comment by dzwdev** [comment]
> Please test #1903

how to build onionshare?

**Comment by dzwdev** [comment]
`poetry install                                             ✔  desktop  

Installing dependencies from lock file

pyproject.toml changed significantly since poetry.lock was last generated. Run `poetry lock [--no-update]` to fix the lock file.
`
