### ISSUE TITLE
error: 'NoneType' object has no attribute 'q'

### ISSUE THREAD

**Issue by dzwdev** [onionshare/onionshare#1909]
when opening onionshare i get:
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/onionshare/tab/tab.py", line 533, in timer_callback
    r = mode.web.q.get(False)
        ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'q'

onionshare version: 2.6.2

Os info:
Operating System: Manjaro Linux 
KDE Plasma Version: 6.1.2
KDE Frameworks Version: 6.3.0
Qt Version: 6.7.2
Kernel Version: 6.9.8-1-MANJARO (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i5-6300U CPU @ 2.40GHz
Memory: 11,6 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 520
Manufacturer: Dell Inc.
Product Name: Latitude 7480

**Comment by SaptakS** [comment]
Did you install it through flatpak or snapcraft?

**Comment by dzwdev** [comment]
> Did you install it through flatpak or snapcraft?

i have installed it from the arch linux user repo AUR
and i have changed to EndeavourOS and i get the same error when clicking in: chat anonymous
and when closing the tab i also get:

`Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/onionshare/__init__.py", line 259, in shutdown
    main_window.cleanup()
  File "/usr/lib/python3.12/site-packages/onionshare/main_window.py", line 288, in cleanup
    self.tabs.cleanup()
  File "/usr/lib/python3.12/site-packages/onionshare/tab_widget.py", line 104, in cleanup
    self.tabs[tab_id].cleanup()
  File "/usr/lib/python3.12/site-packages/onionshare/tab/tab.py", line 675, in cleanup
    self.get_mode().web.cleanup()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'cleanup'
`
